services:
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis

  celery:
    build: .
    container_name: celery_worker
    command: celery -A project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A project beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    env_file:
      - .env

volumes:
  postgres_data:
